version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    networks:
      - clarusnet

  myapp:
    image: slhttnunlu/bookstoreapi:least #budada imagin adini yaziyoruz herhangibir sey yazabiliriz isim olarak ama sonrasinda docker hub repomuza atacaksak bu sekilde kullanici adi image adi seklinde yazmak mantikli burda docker hub daki bir imaj da yazilabilir
    container_name: myapp
    restart: always #bunu yazmamizin sebebi db contanieri calisip kendine gelene adar uygulama db ye baglanirsa hata alip patlayabilir bunu yazarak hata alirsan restart et tekrar dene anlaminda komut vermis oluyoruz bunun yerine depend on da verilebilir
    depends_on:
      - database
    ports:
      - "80:80"  
    networks:
      - clarusnet

networks:
  clarusnet: